OhGoodTeam/OhGoodFood

- pom.xml
- src/main/java/kr/co/ohgoodfood/dto/Account.java
- src/main/java/kr/co/ohgoodfood/dto/Admin.java
- src/main/java/kr/co/ohgoodfood/dto/Alram.java
- src/main/java/kr/co/ohgoodfood/dto/Bookmark.java
- src/main/java/kr/co/ohgoodfood/dto/Image.java
- src/main/java/kr/co/ohgoodfood/dto/Order.java
- src/main/java/kr/co/ohgoodfood/dto/Paid.java
- src/main/java/kr/co/ohgoodfood/dto/Product.java
- src/main/java/kr/co/ohgoodfood/dto/Review.java
- src/main/java/kr/co/ohgoodfood/dto/Stroe.java
kr.co.ohgoodfood.dto 패키지 안에 기본적인 VO 자바 파일 생성하였습니다.
필드명은 DB명과 동일하며 필터링으로 사용될 여지가 있는 컬럼은 s_ 붙여 추가 선언하였습니다.
> [minjung] feat:VO(dto)자바파일생성

- pom.xml
- src/main/java/kr/co/ohgoodfood/dto/Account.java
- src/main/java/kr/co/ohgoodfood/dto/Admin.java
- src/main/java/kr/co/ohgoodfood/dto/Alram.java
- src/main/java/kr/co/ohgoodfood/dto/Bookmark.java
- src/main/java/kr/co/ohgoodfood/dto/Image.java
- src/main/java/kr/co/ohgoodfood/dto/Order.java
- src/main/java/kr/co/ohgoodfood/dto/Paid.java
- src/main/java/kr/co/ohgoodfood/dto/Product.java
- src/main/java/kr/co/ohgoodfood/dto/Review.java
- src/main/java/kr/co/ohgoodfood/dto/Stroe.java
kr.co.ohgoodfood.dto 에 공용으로 사용될 VO 파일 생성하였습니다. 
필드명은 컬럼명과 동일하며 검색어로 사용될 여지가 있는 컬럼은 s_ 로 추가 선언하였습니다.
> [Admin/minjung] feat:VO(dto)자바파일생성

- src/main/webapp/WEB-INF/views/store/confirmedorder.html
- src/main/webapp/css/confirmedorder.css
> [hwajun] feat. 주문 페이지 확정내역 수정

- .github/CODEOWNERS
> [minjung] fix:CODEOWNERS 수정

- .github/CODEOWNERS
> [minjung] fix :CODEOWNERS 수정

- .github/workflows/auto-reviewer.yml
---
- 리뷰어 자동 설정 파일 수정
---
- Action 토근 설정
---
---
- (선택)
> [minjung] docs:리뷰어설정파일수정

- .github/workflows/auto-reviewer.yml
---
- 또또또또또 리뷰어파일수정
---
- author 변수 추가
---
---
- (선택)
> [minjung] docs:리뷰어파일수정

- src/main/java/kr/co/ohgoodfood/dao/AdminMapper.java
---
- 주석 추가
---
- dto/Admin.java 주석 추가
---
---
- (선택)
> [minjung] docs:주석추가

- src/main/java/kr/co/ohgoodfood/controller/users/UsersController.java
- src/main/java/kr/co/ohgoodfood/service/users/UserServiceImpl.java
---
- 통합시 오류 해결 완료
---
- 통합시 괄호 누락(주의!)
---
---
- (선택)
> [gaeun] feat : controller, serviceImpl 수정

- src/main/java/kr/co/ohgoodfood/controller/users/UsersController.java
- src/main/java/kr/co/ohgoodfood/dao/UserMapper.java
- src/main/java/kr/co/ohgoodfood/dto/Bookmark.java
- src/main/java/kr/co/ohgoodfood/dto/BookmarkDelete.java
- src/main/java/kr/co/ohgoodfood/dto/MainStore.java
- src/main/java/kr/co/ohgoodfood/dto/OrderPayCheck.java
- src/main/java/kr/co/ohgoodfood/dto/UserMainFilter.java
- src/main/java/kr/co/ohgoodfood/dto/UserOrder.java
- src/main/java/kr/co/ohgoodfood/service/users/UserServiceImpl.java
- src/main/java/kr/co/ohgoodfood/service/users/UsersService.java
- src/main/java/kr/co/ohgoodfood/util/StringSplitUtils.java
- src/main/resources/kr/co/ohgoodfood/dao/UserMapper.xml
- src/main/webapp/WEB-INF/views/users/footer.jsp
- src/main/webapp/WEB-INF/views/users/fragment/userOrderList.jsp
- src/main/webapp/WEB-INF/views/users/userBookmark.jsp
- src/main/webapp/WEB-INF/views/users/userMain.jsp
- src/main/webapp/WEB-INF/views/users/userOrders.jsp
- src/main/webapp/css/userorder.css
---
- UserMapper.xml selectAllStore 로직 수정
- 전체 주석 수정 완료
---
- UserMapper.xml selectAllStore에서 데이터에 null값이 있을 시, join 해올때 product_no가 0으로 덮어씌워지는 문제 수정했습니다.
- 전체 주석 양식 맞춰서 수정 완료했습니다.
- 로그인 세션 받아오는것 확인 완료했습니다.
---
---
> [sunjung]fix : mapper 버그 수정 / docs : 전체 주석 다듬기 완료

- src/main/webapp/WEB-INF/views/users/userOrders.jsp
- src/main/webapp/css/userbookmark.css
- src/main/webapp/css/userorder.css
---
- CSS 일부 수정했습니다.
---
- Bookmark css 일부 수정
- orders css 일부 수정
---
---
> [sunjung]style : css 일부 수정

- src/main/java/kr/co/ohgoodfood/controller/users/UsersController.java
- src/main/resources/kr/co/ohgoodfood/dao/UserMapper.xml
- src/main/webapp/WEB-INF/views/users/userMain.jsp
---
- 왜인지 mapper.xml 3개가 다 날라갔던 문제 해결 완료
---
- 왜 날라갔었을까요..  mapper 살려놓고 pin값 뜨는거 확인 완료했습니다.
---
---
- (선택)
> [sunjung]fix : mapper 없어진 문제 수정 완료

- src/main/java/kr/co/ohgoodfood/controller/users/UsersController.java
- src/main/java/kr/co/ohgoodfood/dao/UserMapper.java
- src/main/java/kr/co/ohgoodfood/dto/Bookmark.java
- src/main/java/kr/co/ohgoodfood/dto/MainStore.java
- src/main/java/kr/co/ohgoodfood/dto/PickupStatus.java
- src/main/java/kr/co/ohgoodfood/dto/UserMainFilter.java
- src/main/java/kr/co/ohgoodfood/dto/UserOrder.java
- src/main/java/kr/co/ohgoodfood/service/users/UserServiceImpl.java
- src/main/java/kr/co/ohgoodfood/service/users/UsersService.java
- src/main/resources/kr/co/ohgoodfood/dao/UserMapper.xml
- src/main/webapp/WEB-INF/views/users/fragment/userOrderList.jsp
- src/main/webapp/WEB-INF/views/users/userBookmark.jsp
- src/main/webapp/WEB-INF/views/users/userMain.jsp
- src/main/webapp/WEB-INF/views/users/userOrders.jsp
- src/main/webapp/css/userbookmark.css
- src/main/webapp/css/usermain.css
- src/main/webapp/css/userorder.css
---
- map에 center 재조정 기능 추가
- center 재조정 할 시 가게 modal 닫히도록 설정
- 검색 필터링 들어갈 시 위&경도 필터링 제외하도록 설정
- 그외 자잘한 css & js 오류 수정
- 주석 깔끔하게 보정
---
- map에 center 재조정 기능 추가 했으며, center 재조정 할 시 가게 modal 닫히도록 설정했습니다. center 값 재조정에 따라 반경 안에 있는 가게 pin들이 뜹니다.
- 검색 필터링 들어갈 시 위&경도 필터링 제외하도록 설정했습니다. 검색어 사용시 위&경도 제외하고 모든 저장된 가게들이 검색어로 필터링된 결과들이 나옵니다.
- 예약 가능한 가게 필터링에 매진시 뜨지 않도록 조정했습니다.
- 그외 usermain화면 js 로직 좀 명확하게 변경했습니다. (이 부분은 기능엔 변동 없습니다.)
- 개발한 기능들 주석 깔끔하게 보정했습니다.
---
---
> [sunjung]feat: map에 center 재조정 기능 추가 / fix : 검색시 위&경도 제외 조건 추가, 그외 주석 수정 및 자잘한 에러들 전부 수정

- src/main/java/kr/co/ohgoodfood/controller/users/UsersController.java
- src/main/java/kr/co/ohgoodfood/dao/UserMapper.java
- src/main/java/kr/co/ohgoodfood/dto/ProductDetail.java
- src/main/java/kr/co/ohgoodfood/service/users/UserServiceImpl.java
- src/main/java/kr/co/ohgoodfood/service/users/UsersService.java
- src/main/resources/kr/co/ohgoodfood/dao/UserMapper.xml
- src/main/webapp/WEB-INF/views/users/userBookmark.jsp
- src/main/webapp/WEB-INF/views/users/userProductDetail.jsp
- src/main/webapp/css/userPaid.css
- src/main/webapp/css/userProductDetail.css
- src/main/webapp/css/userReviewList.css
- src/main/webapp/css/userReviewWrite.css
- src/main/webapp/css/userSignup.css
- src/main/webapp/css/userbookmark.css
- src/main/webapp/css/userfooter.css
- src/main/webapp/css/userheader.css
- src/main/webapp/css/usermain.css
- src/main/webapp/css/userorder.css
- src/main/webapp/css/userpiadfail.css
---
- 상세페이지 북마크 기능 추가
- css 글꼴 추가
---
- 상세페이지 북마크 기능 추가
- 북마크 설정 추가
- css 글꼴 추가
---
---
- (선택)
> [gaeun] feat : 북마크 기능 추가 및 css 글꼴 설정 추가

- src/main/webapp/css/userProductDetail.css
- src/main/webapp/css/userReviewList.css
- src/main/webapp/css/usermypage.css
---
- 이미지 테두리 수정
---
- (구체적인 작업 내역이나 변경 사항을 적어 주세요)
---
---
- (선택)
> [gaeun] feat : css 수정

- src/main/webapp/WEB-INF/views/users/userReviewWrite.jsp
---
- 리뷰 중복 제출 방지
---
- 리뷰 중복 제출 방지
---
---
- (선택)
> [gaeun] fix : 리뷰 제출 중복 오류 해결

- src/main/resources/kr/co/ohgoodfood/dao/UserMapper.xml
---
- 회원가입시 500포인트 적립
---
- 회원가입시 500포인트 적립
---
---
- (선택)
> [gaeun] feat : 회원가입시 500포인트 적립

- src/main/webapp/WEB-INF/views/store/mypage.jsp
- src/main/webapp/css/storesignup.css
---
- 마이페이지 탈퇴하기 버튼 삭제
- 회원가입 버튼 css 폰트 추가
---
- 마이페이지 필요없는 탈퇴하기 버튼 삭제
- 회원가입 버튼 누락된 css 폰트 추가
---
---
- (선택)
> [eunhyo] feat: 마이페이지 탈퇴하기 버튼 삭제, 회원가입 버튼 css 폰트 추가

- src/main/java/kr/co/ohgoodfood/config/MvcConfig.java
- src/main/java/kr/co/ohgoodfood/controller/admin/AdminController.java
- src/main/java/kr/co/ohgoodfood/service/common/ScheduleServiceImpl.java
- src/main/java/kr/co/ohgoodfood/service/store/StoreServiceImpl.java
- src/main/resources/log4j.xml
- src/main/webapp/WEB-INF/views/store/signup.jsp
- src/main/webapp/WEB-INF/views/users/userReviewWrite.jsp
---
- 서버 4차 배포용
- 스케쥴드 비동기 처리 추가
- 이미지 업로드 검증 추가
---
- 스케쥴드 쓰레드에 비동기 처리를 통해 로직 꼬임 방지
- csrf 및 파일 업로드 공격 방지를 위해 업로드 검증 로직 추가
---
---
- (선택)
> [minjung] feat: 서버 4차 배포용. 비동기 처리 및 스케줄링 기능 개선, 이미지 업로드 검증 추가

- src/main/java/kr/co/ohgoodfood/controller/admin/AdminController.java
- src/main/java/kr/co/ohgoodfood/dao/AdminMapper.java
- src/main/java/kr/co/ohgoodfood/service/admin/AdminServiceImpl.java
- src/main/resources/kr/co/ohgoodfood/dao/AdminMapper.xml
- src/main/webapp/WEB-INF/views/admin/managedalarm.jsp
- src/main/webapp/WEB-INF/views/admin/managedorders.jsp
- src/main/webapp/WEB-INF/views/admin/managedpaids.jsp
- src/main/webapp/WEB-INF/views/admin/managedreviews.jsp
- src/main/webapp/WEB-INF/views/admin/managedstore.jsp
- src/main/webapp/WEB-INF/views/admin/managedusers.jsp
---
- 서버 5차 배포본
- 어드민 서비스 개선
---
- 어드민 서비스 mapper 수정 
- 어드민 서비스 미적용시 오류 메세지 출력
---
---
- (선택)
> [minjung] feat:서버 5차 배포본. 관리자 페이지 기능 개선 및 피드백 메시지 추가
